# Generated by Django 2.2.4 on 2019-08-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_customnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
