# Generated by Django 4.0 on 2022-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20190827_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
