# Generated by Django 4.0 on 2022-03-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('friends', '0005_customnotification_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customnotification',
            old_name='unread',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='customnotification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customnotification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
